include:
  - project: skyline-platform/devops/vp-pipeline
    ref: master
    file: stages/analysis.yml
  - project: skyline-platform/devops/vp-pipeline
    ref: master
    file: stages/post.yml

stages:
  - analysis
  - post

# DISABLE UNUSED JOBS
code_quality:
  rules:
    - when: never